# Generated by Django 5.0.7 on 2024-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordersmodel_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='delivery_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
