# Generated by Django 5.0.7 on 2024-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordersmodel_created_at_ordersmodel_delivery_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='delivery_at',
            field=models.DateTimeField(),
        ),
    ]
